apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-registry
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RenyYon/gitops-nifi-registry
    targetRevision: main
    path: helm/nifi-registry

  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-registry

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
